services:

  nginx:
    container_name: nginx
    image: nginx
    build: requirements/nginx
    restart: always
    ports:
      - "443:443"
    networks:
      - containers_network
    depends_on:
      - wordpress
    volumes:
      - wordpress_volume:/var/www/html

  wordpress:
    container_name: wordpress
    image: wordpress
    build: requirements/wordpress
    restart: always
    env_file:
      - .env
    networks:
      - containers_network
    depends_on:
      - mariadb
    volumes:
      - wordpress_volume:/var/www/html

  mariadb:
    container_name: mariadb
    image: mariadb
    build: requirements/mariadb
    restart: always
    env_file:
      - .env
    networks:
      - containers_network
    volumes:
      - mariadb_volume:/var/lib/mysql

  ftp:
    container_name: ftp
    image: ftp
    build: requirements/bonus/ftp
    restart: always
    ports:
      - "21:21"
      - "15000-15030:15000-15030"
    env_file:
      - .env
    volumes:
      - wordpress_volume:/var/www/html

networks:
  containers_network:
    driver: bridge

volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/tibarike/data/mariadb
  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/tibarike/data/wordpress
