services:
  nginx:
    container_name: nginx
    image: nginx
    build: requirements/nginx
    restart: always
    env_file:
      - .env
    ports:
      - "443:443"
    networks:
      - containers_network
    depends_on:
      wordpress:
        condition: service_healthy
    volumes:
      - wordpress_volume:/var/www/html
  wordpress:
    container_name: wordpress
    image: wordpress
    build: requirements/wordpress
    restart: always
    env_file:
      - .env
    networks:
      - containers_network
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wordpress_volume:/var/www/html
    healthcheck:
      test: [ "CMD-SHELL", "cat", "/dev/null", ">", "/dev/tcp/127.0.0.1/9000" ]
      interval: 10s
      timeout: 7s
      retries: 3
  mariadb:
    container_name: mariadb
    image: mariadb
    build: requirements/mariadb
    restart: always
    env_file:
      - .env
    networks:
      - containers_network
    volumes:
      - mariadb_volume:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "taoufiq", "-p${MYSQL_USR_PASS}", "--port=${MARIADB_PORT}", "--silent" ]
      interval: 10s
      timeout: 7s
      retries: 3

networks:
  containers_network:
    driver: bridge

volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/tibarike/data/mariadb
  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/tibarike/data/wordpress
