FROM debian:bullseye

RUN apt-get update -y && apt-get install --no-install-recommends -y mariadb-server

RUN mkdir -p /run/mysql && chown -R mysql:mysql /run/mysql

COPY tools/script.sh /usr/local/bin/script.sh

RUN chmod +x /usr/local/bin/script.sh

WORKDIR /home/tibarike/Desktop/inception/srcs/requirements/mariadb/

EXPOSE 3306

ENTRYPOINT [ "/usr/local/bin/script.sh" ]