FROM debian:bookworm

RUN apt-get update && apt-get install -y --no-install-recommends vsftpd

RUN mkdir -p /var/run/vsftpd/empty /var/www/html

COPY tools/vsftpd.conf /etc/vsftpd/

COPY tools/script.sh /

RUN chmod +x /script.sh

ENTRYPOINT [ "/script.sh" ]