FROM debian:bookworm

RUN apt-get update && \
    apt-get install -y --no-install-recommends vsftpd

RUN mkdir -p /var/run/vsftpd/empty /var/www/html

COPY tools/vsftpd.conf /etc/vsftpd.conf

COPY tools/script.sh /usr/local/bin/script.sh

RUN chmod +x /usr/local/bin/script.sh

ENTRYPOINT [ "/usr/local/bin/script.sh" ]