server {
    listen 443 ssl; 

    ssl_certificate /etc/nginx/ssl/nginx_cert.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx_cert_key.key;
    ssl_protocols TLSv1.3;

    root /var/www/html;
    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ .php$ {
        fastcgi_pass wordpress:9000;
        include snippets/fastcgi-php.conf;
    }
}
