FROM debian:bookworm

RUN apt-get update && \
    apt-get install --no-install-recommends -y php8.2-fpm php8.2-mysql php-redis curl ca-certificates && \
    curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && \
    chmod +x wp-cli.phar && \
    mv wp-cli.phar /usr/local/bin/wp

RUN mkdir -p /var/www/html /run/php && \
    mkdir -p /run/php && chown -R www-data:www-data /run/php

COPY tools/script.sh /

COPY tools/php-fpm.conf /etc/php/8.2/fpm/pool.d/www.conf

RUN chmod +x /script.sh

ENTRYPOINT [ "/script.sh" ]