FROM debian:bookworm

RUN apt-get update && \
    apt-get install --no-install-recommends -y php7.4-fpm php7.4-mysql curl netcat ca-certificates && \
    curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && chmod 777 wp-cli.phar && mv wp-cli.phar /usr/local/bin/wp && \
    mkdir -p /var/www/html /run/php && chown -R www-data:www-data /var/www/html && \
    mkdir -p /run/php && chown -R www-data:www-data /run/php

COPY tools/script.sh /usr/local/bin/script.sh
COPY tools/php-fpm.conf /etc/php/7.4/fpm/pool.d/www.conf

RUN chmod +x /usr/local/bin/script.sh

EXPOSE 9000

ENTRYPOINT [ "/usr/local/bin/script.sh" ]