FROM debian:bullseye

RUN apt-get update && \
    apt-get install --no-install-recommends -y php7.4-fpm php7.4-mysql curl mariadb-client && \
    curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && chmod 777 wp-cli.phar && mv wp-cli.phar /usr/local/bin/wp && \
    mkdir -p /var/www/html /run/php && chown -R www-data:www-data /var/www/html

COPY tools/script.sh /usr/local/bin/script.sh

RUN chmod +x /usr/local/bin/script.sh

WORKDIR /home/tibarike/Desktop/inception/srcs/requirements/wordpress/

EXPOSE 9000

ENTRYPOINT [ "/usr/local/bin/script.sh" ]