FROM debian:bookworm

RUN apt-get update && \ 
    apt-get install --no-install-recommends -y nginx

COPY tools/nginx.conf /etc/nginx/sites-enabled/default
COPY tools/image.png /
COPY tools/index.html /

ENTRYPOINT [ "nginx", "-g", "daemon off;" ]
