FROM debian:bullseye

RUN apt-get update && \ 
    apt-get install -y php7.4-fpm php7.4-mysql curl mariadb-client

COPY tools/script.sh /usr/local/bin/script.sh

RUN chmod +x /usr/local/bin/script.sh

WORKDIR /home/tibarike/Desktop/inception/srcs/requirements/nginx/

EXPOSE 443

ENTRYPOINT [ "/usr/local/bin/script.sh" ]
