FROM debian:bookworm

RUN apt-get update && \
    apt-get install -y --no-install-recommends redis-server

RUN sed -i "s/127.0.0.1 -::1/0.0.0.0/" /etc/redis/redis.conf && \
    sed -i "s/protected-mode yes/protected-mode no/" /etc/redis/redis.conf && \
    sed -i "s/daemonize yes/daemonize no/" /etc/redis/redis.conf

ENTRYPOINT [ "redis-server", "/etc/redis/redis.conf" ]